### ISSUE TITLE
AR Test

### ISSUE THREAD

**Issue by weiweilwl** [apoorvalal/ivDiag#10]
Hi,

Can I ask how to interpret the AR_test? In my understanding and after reading the referred article being able to reject the null indicate the instrument is not suitable?

I got the following results:
$AR
$AR$Fstat
         F        df1        df2          p 
    8.5742     1.0000 34808.0000     0.0034

**Comment by xuyiqing** [comment]
A small p means that one can reject the null of no effect assuming the identifying assumptions (e.g., IV exogeneity, including unconfoundedness & exclusion restriction) are met.
